'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BookingSystemDataEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BookingSystemDataEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblBookings() As DbSet(Of tblBooking)
    Public Overridable Property tblEnquires() As DbSet(Of tblEnquire)
    Public Overridable Property tblSeats() As DbSet(Of tblSeat)
    Public Overridable Property tblUserLists() As DbSet(Of tblUserList)

End Class
