'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblBooking
    Public Property BookingID As Integer
    Public Property Username As String
    Public Property Seat As Integer

    Public Overridable Property tblSeat As tblSeat
    Public Overridable Property tblUserList As tblUserList

End Class
